// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQi40aQkSsksMUyB07_U5m2OkZw-BqNI',
    appId: '1:910480449358:web:a027ebb9b05ac62fe9881f',
    messagingSenderId: '910480449358',
    projectId: 'flutter-application-1-d114c',
    authDomain: 'flutter-application-1-d114c.firebaseapp.com',
    storageBucket: 'flutter-application-1-d114c.firebasestorage.app',
    measurementId: 'G-BM721RBD3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBuMBDcwT27ELwD2ukEr2W93SOIeoGoD4',
    appId: '1:910480449358:android:2f23d1460f90d4a5e9881f',
    messagingSenderId: '910480449358',
    projectId: 'flutter-application-1-d114c',
    storageBucket: 'flutter-application-1-d114c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ95YI7-0QYpkqoMKWSD1HgM1JHwB8Exs',
    appId: '1:910480449358:ios:3b8b3d0714ed818ee9881f',
    messagingSenderId: '910480449358',
    projectId: 'flutter-application-1-d114c',
    storageBucket: 'flutter-application-1-d114c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ95YI7-0QYpkqoMKWSD1HgM1JHwB8Exs',
    appId: '1:910480449358:ios:3b8b3d0714ed818ee9881f',
    messagingSenderId: '910480449358',
    projectId: 'flutter-application-1-d114c',
    storageBucket: 'flutter-application-1-d114c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSQi40aQkSsksMUyB07_U5m2OkZw-BqNI',
    appId: '1:910480449358:web:1a9658ad9ebbd3f2e9881f',
    messagingSenderId: '910480449358',
    projectId: 'flutter-application-1-d114c',
    authDomain: 'flutter-application-1-d114c.firebaseapp.com',
    storageBucket: 'flutter-application-1-d114c.firebasestorage.app',
    measurementId: 'G-402KYDS9PH',
  );

}